project_id = "vcrsuvzsqivcamzlvluz"

[functions.google-calendar-sync]
verify_jwt = false

[functions.send-deliverable-notification]
verify_jwt = true

[functions.send-contract-email]
verify_jwt = true

[functions.send-quote-email]
verify_jwt = true

[functions.send-receipt-email]
verify_jwt = true

[functions.payment-reminder]
verify_jwt = false

[functions.clean-old-notifications]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = true

[functions.check-notifications]
verify_jwt = true

[functions.validate-gallery-password]
verify_jwt = false
